#!/bin/sh

set -eu

composer install

export PATH="$(pwd)/vendor/bin:$PATH"

cp .env.github .env

eval $(grep -v '^#' .env)

composer wp-install
composer install

if [ "$(wp-install --status)" = "full" ]; then
    wp-install --serve &
fi

composer test