#!/bin/sh

set -eu

composer install

cp .env.github .env
export PATH="$(pwd)/vendor/bin:$PATH"

composer wp-install

if [ "$(wp-install --status)" = "full" ]; then
    wp-install --serve &
fi

composer test
