#!/bin/sh

set -eu

help() {
    echo "
    Install WordPress

    usage: $(basename $0) [options]

    Options

        --env-file PATH
            Path to a dot env file

        --wp-composer-file PATH
            Path to the composer file to be used for WP Defaults to
            composer.wp-install.json

        --full
            Do full installation. Only required for functional and acceptance
            tests

        --force
            Force reinstallation

        --serve
            Serve the installation using wp-cli

        --status
            Print the status of the installation. 'basic' 'full' or 'broken'

        --theme-path
            Theme path to link to the installation

        --theme-name
            Theme name to activate

        --wp-core-version VERSION
            WordPress core version to install. Defaults to 'latest'

        --post-install
            Path to a script which executed after the full installation in
            the wp directory but before creating the db dump for functional
            and acceptance testing. You can WP-CLI to create dummy posts for
            example.


    "
}

theme_path=
theme_name=
full_install=
post_install_script=
env_file=.env
wp_composer_file=composer.wp-install.json
force=
serve=
print_status=
core_version="${WPTT_CORE_VERSION:-latest}"

while true; do
    case "${1:-}" in
    -f|--full)
        shift
        full_install=1
        ;;
    --force)
        shift
        force=1
        ;;
    --env-file)
        shift
        env_file="$1"
        shift
        ;;
    --wp-composer-file)
        shift
        wp_composer_file="$1"
        shift
        ;;
    --wp-core-version)
        shift
        core_version="$1"
        shift
        ;;
    --post-install)
        shift
        post_install_script="$1"
        shift
        ;;
    --serve)
        shift
        serve=1
        ;;
    --status)
        shift
        print_status=1
        ;;
    --theme-path)
        shift
        theme_path="$1"
        shift
        ;;
    --theme-name)
        shift
        theme_name="$1"
        shift
        ;;
    -h|--help)
        help && exit 0
        ;;
    "")
        break
        ;;
    *)
        >&2 echo "Unknown arg $1"
        >&2 echo "See --help"
        exit 2
        ;;
    esac
done


if [ ! -x "$(which jq)" ]; then
	>&2 echo "jq cli tool missing"
	exit 2
fi

if [ ! -f composer.json ]; then
	>&2 echo "No composer.json?"
	exit 1
fi

if [ ! -f "$wp_composer_file" ]; then
	>&2 echo "Cannot find $wp_composer_file"
	exit 1
fi

if [ "$post_install_script" != "" ];then
    if [ ! -x "$post_install_script" ]; then
        >&2 echo "$post_install_script is not an executable"
        exit 1
    fi

    # get absolute path
    post_install_script="$(
        cd "$(dirname "$post_install_script")"
        echo "$(pwd)/$(basename "$post_install_script")"
    )"
fi

if [ "$env_file" != "" ]; then
    if [ ! -f "$env_file" ]; then
        >&2 echo "Cannot read env file $env_file"
        exit 1
    fi

    eval $(grep -v '^#' "$env_file")
fi

target="$WPTT_INSTALL_DIR"
success_flag="$target/install_ok"
db_name="$WPTT_DB_NAME"
db_user="$WPTT_DB_USER"
db_password="$WPTT_DB_PASSWORD"
db_host="$WPTT_DB_HOST"

if [ "$serve" = "1" ]; then
    if [ -f "${WPTT_INSTALL_DIR}/web/wp-config.php" ]; then
        cd "${WPTT_INSTALL_DIR}/web"
        exec wp server --host=0.0.0.0
    fi

    >&2 echo "Bad or non-full WP installation at ${WPTT_INSTALL_DIR}"
    exit 3
fi

if [ "$print_status" = "1" ]; then
    if [ ! -f "$success_flag" ]; then
        echo broken
        exit
    fi

    if [ -f "${WPTT_INSTALL_DIR}/web/wp-config.php" ]; then
        echo full
        exit
    fi

    echo basic
    exit
fi


if [ "$full_install" = "1" ]; then
    wp_admin="$WPTT_SITE_ADMIN_USERNAME"
    wp_admin_password="$WPTT_SITE_ADMIN_PASSWORD"
    site_url="http://$WPTT_SITE_HOST"
fi

mkdir -p "$target"
target="$(cd "$target" && pwd)" # get absolute path
wp_core_dir="$target/web"
src_dir="$(pwd)"

type="$(jq -r .type composer.json)"

if [ "$type" != "wordpress-plugin" ]; then
	>&2 echo "Only wordpress plugins are supported for now. Set \"type\" to \"wordpress-plugin\" in composer.json"
	exit 1
fi

project_name="$(jq -r .name composer.json  | cut -d / -f 2)"

mysql_cli() {
    mysql --host $db_host --user="$db_user" --password="$db_password" $@
}

create_db() {
    if [ "$(echo "SHOW DATABASES like '$db_name';" | mysql_cli | tail -n 1)" = "$db_name" ]; then
        >&2 echo "Dropping existing database $db_name"
        echo "DROP DATABASE $db_name;" | mysql_cli
    fi

    echo "CREATE DATABASE $db_name;" | mysql_cli
}


get_wp_core() {
    (
        mkdir -p "$wp_core_dir"
        cd "$wp_core_dir"

        wp core download --version=$core_version

        # Remove plugins shipped with the core
        rm -rf wp-content/plugins/hello.php
        rm -rf wp-content/plugins/akismet/
    )
}

get_wp_plugins() {
    (
        cp "$wp_composer_file" "$target/composer.json"
        cd "$target"
        composer install

        ln -fs ../../../.. "${wp_core_dir}/wp-content/plugins/$project_name"
    )
}



extra_wp_config="
define('WP_ENV', 'test');
define('WPTT_INSTALL', true);
require_once __DIR__ . '/../vendor/autoload.php';
if ( is_readable( __DIR__ . '/../../tests/wptt-wp-config.php') )  {
 	require_once __DIR__ . '/../../tests/wptt-wp-config.php';
}
"

install_wp() {
    (
        cd "$wp_core_dir"

        echo "$extra_wp_config" | wp config create \
            --dbname="$db_name" \
            --dbuser="$db_user" \
            --dbpass="$db_password" \
            --dbhost="$db_host" \
            --force=true \
            --extra-php


        wp core install \
            --url="$site_url" \
            --title="Testing installation for $project_name" \
            --admin_user="$wp_admin" \
            --admin_password="$wp_admin_password" \
            --admin_email=admin@wp.test \

        wp rewrite structure '/%postname%/'

        cd wp-content/plugins

        # activate all plugins
        for plugin in *; do
            if [ -d "$plugin" ]; then
                wp plugin activate "$plugin"
            fi
        done

        if [ "$theme_name" != "" -a "$theme_path" != "" ]; then
            ln -fs "../../../../$theme_path" "${wp_core_dir}/wp-content/themes/$theme_name"
            wp theme activate "$theme_name"
        fi

        cd "$wp_core_dir"

        if [  "$post_install_script" != "" ]; then
            "$post_install_script"
        fi

	    wp db export "$target/dump.sql"

    )
}


if [ -f "$success_flag" -a "$force" != "1" ]; then
    >&2 echo "WP install already ok. Skipping. Force reinstall with --force"
    exit 0
else
    >&2 echo "Removing installation from $target (if any)"
    rm -rf "$target"
    mkdir -p "$wp_core_dir"
fi

create_db
get_wp_core
get_wp_plugins

if [ "$full_install" = "1" ]; then
    install_wp
fi

date > "$success_flag"

>&2 echo "WP installed succesfully to $wp_core_dir"